### PR TITLE
test python 3.7 through 3.11

### PR DESCRIPTION
**Pull request by altendky**

### CODE REVIEW

**Comment by altendky** [comment]
So, do you want to drop 3.7?  Only check the safety in 3.10?  Or...

**Comment by fabianp** [comment]
yeah, I'm happy to drop 3.7

**Comment by altendky** [comment]
kick ci

**Comment by altendky** [comment]
Not beautiful, but a first pass from which there can be refinement anyways.  Checks are run on 3.10 as I usually use one version behind the latest release for this.  The point is to run the checks, not check if they have bugs on the latest Python version.  The tests are run on all supported Python versions, 3.7 through 3.11.  I left safety running on everything except 3.7 right now.

I'm good with this going in as is, if you are ok with it.  If we find stuff to tweak we can do it piece by piece.  Let me know what you think.

**Comment by fabianp** [comment]
thanks! LGTM

**Pull request merged**
