### PR TITLE
Add support for coroutine profiling

### PR DESCRIPTION
**Pull request by d-ryzhikov**
This PR adds support for using `@profile` decorator on coroutines (both generator based coroutines and ones defined with `async def` statements).
Support for Python versions <3.4 is dropped.

### CODE REVIEW

**Comment by delijati** [comment]
can this be merged!

**Comment by fabianp** [comment]
Although I would like to see support for coroutines, I'm not comfortable with this PR changing the project organization, like distributing existing code over multiple files, as well as with the name of these files, like ```__main__.py```

**Comment by d-ryzhikov** [comment]
`__main__.py` makeы memory profiler an executable package. And, IMHO, splitting the library into multiple small files would make maintenance easier.
@fabianp, if I manage to rewrite it keeping the memory_profiler.py untouched (and adding 1 extra file for asyncio support), would you be more comfortable with that?

**Comment by fabianp** [comment]
thanks for your answer @d-ryzhikov and apologies for my slow response. 

This PR has two many changes in the code for me to review those changes and guarantee that it won't break other user cases, I hope you can understand that. Also, I would like to keep the code inside a single file (two if you count mprof) so that it can be more easily incorporated into other projects.

How many lines of code do you think adding support for coroutine profiling would add to ```memory_profiler.py``` if we were to keep the project with the current organization?

**Comment by d-ryzhikov** [comment]
@fabianp , the async support itself won't be more than 40 lines. And it will have to be in a separate file if the support of Python version prior to 3.3 is necessary, because it will make use of `yield from` syntax (which was added in Python 3.3).

**Comment by fabianp** [comment]
I'm fine with coroutine support breaking for 3.3 as long as the other functionality still work in that version. Do you think this way it would be possible to have everything in the same file?

**Comment by d-ryzhikov** [comment]
@fabianp , yes. If <3.3 support isn't neccessary, everything can be kept in 1 file.

**Comment by yoav-orca** [comment]
@fabianp @d-ryzhikov I would love to have this feature in, do you need help making the new PR?

**Comment by d-ryzhikov** [comment]
sorry 4 the wait
@fabianp,  I reverted the 1-file structure of the code as requested dropping support of python <3.4 (including python2). I also did a little cleanup of the python2 specific code. Python>=3.4 is now required for the package (see [this](https://github.com/pythonprofilers/memory_profiler/pull/255/files#diff-2eeaed663bd0d25b7e608891384b7298R43)).

**Comment by fabianp** [comment]
Merged. Thanks a lot of the hard and continued work!

**Pull request merged**
