### PR TITLE
Modernize infrastructure

### PR DESCRIPTION
**Pull request by Juanlu001**
I switched back to pip (I am a huge conda fan... but with these little dependencies is not necessary anymore I think!) and added more Python versions to the matrix, to make sure everything works up to Python 3.6 (with optional 3.7 tests).

### CODE REVIEW

**Comment by fabianp** [comment]
+1 from me as long as travis is happy

**Comment by Juanlu001** [comment]
Wow, it worked on PyPy as well :)

**Comment by Juanlu001** [comment]
Merging, and enough for today. Thanks again!

**Comment by fabianp** [comment]
to you!

**Pull request merged**
