### PR TITLE
WIP: Memory calculation with deltas

### PR DESCRIPTION
**Pull request by Juanlu001**
This is my attempt to take over #123. Will probably inherit the same problems in Python 2.

### CODE REVIEW

**Comment by Juanlu001** [comment]
Oops @fabianp you have to configure Travis CI in this repo :)

**Comment by fabianp** [comment]
Thanks @Juanlu001 . Don't have time to review in detail but code looks good to me. Feel free to merge when you consider that it works on both python2 and python3.

I'll try to set up travis tomorrow.

**Comment by Juanlu001** [comment]
Closing and reopening to trigger CI.

**Comment by Juanlu001** [comment]
Sorry @fabianp, I'm making noise because I think the CI is not configured yet.

**Comment by fabianp** [comment]
OK I just created it now: https://travis-ci.org/pythonprofilers/memory_profiler. Can you try again?

**Comment by Juanlu001** [comment]
Thanks! Worked now, will fix the remaining issues this week.

**Comment by Juanlu001** [comment]
The unicode test already passed. However, the tests are a bit slow (15 minutes and counting...). @fabianp what do you think of installing psutil in Travis CI builds?

**Comment by fabianp** [comment]
Its really strange that the tests take so long, it should not be this way. If a test is taking so long we need to change the tests, its not useful to have a test that cannot be run half of the time.

**Comment by Juanlu001** [comment]
I changed the Travis config tu use the docker container (no sudo) in the hope that this would accelerate the tests, but I don't think it is the case.

**Comment by fabianp** [comment]
OK lets then install psutils on travis. If we do that then we might as well just make psutil a dependency (as you suggested), since the code to run without psutils seems to be slow and/or buggy.

**Comment by Juanlu001** [comment]
:tada: There we have it!

**Comment by Juanlu001** [comment]
In it goes then!

**Pull request merged**
