### PR TITLE
Allow passing args to profiled script or module

### PR DESCRIPTION
**Pull request by axlan**
Also attempted to clarify usage
Made to address https://github.com/pythonprofilers/memory_profiler/issues/179

### CODE REVIEW

**Comment by fabianp** [comment]
Thanks @axlan ! At first sight looks good to me, I'll try it tomorrow and merge if OK.

**Comment by naggie** [comment]
Saved me some time. Thanks!

**Comment by fabianp** [comment]
merged, thanks!

**Comment by philip-schiff-cortica** [comment]
Should this be reflected in memory_profiler 0.51.0?  python3 memory_profiler -m my_script.py my_script_args results in "unrecognized arguments" to memory_profiler (python 3.6)

**Pull request merged**
