### PR TITLE
mprof attach option - profile existing process

### PR DESCRIPTION
**Pull request by cr-dani-koretsky**
Hi,

`mprof run --attach explorer.exe`
`mprof attach explorer.exe`

I think this tool is super lean and useful, I had a use case the library supports but mprof didn't.
This PR adds an "attach" alias for "run --attach" using pid/process name for an existing process.

I will test it myself soon, any comments?

### CODE REVIEW

**Comment by cr-dani-koretsky** [comment]
I've tested the code and fixed so it works well.
Can someone help me merge?

**Comment by fabianp** [comment]
Hi  Dani,

i'll take a look as soon as possible.

Cheers

**Comment by cr-dani-koretsky** [comment]
Sounds great, thanks!
I've been using this for a week now, it's very helpful for profiling
services or special processes.

I'm not sure if it might be possible to even support attaching to python
processes, maybe we can make a passive "@profile" decorator that is only
used after we attach.

In any case the current form seems to work for my usage.

**Comment by fabianp** [comment]
code looks good to me, functionality is a clear improvement. Thanks @cr-dani-koretsky for the contribution!!

**Pull request merged**
