### PR TITLE
replace deprecated optparse with argparse

### PR DESCRIPTION
**Pull request by skwbc**
Related to pull request #2 and #5. These pull requests were created in May 2012.
Now it is November 2016, I think that Python 2.6 and 3.1 are rarely used.
What is your idea?

### CODE REVIEW

**Comment by Juanlu001** [comment]
This PR now has conflicts, would you mind rebasing to check that everything is correct?

**Comment by skwbc** [comment]
@Juanlu001 
Thank you for your comment.
Rebased and resolved conflicts of this pull request.

**Comment by Juanlu001** [comment]
Thanks a lot @skwbc! The code looks good and all tests passed, so I think this is good to go. Merging!

**Comment by fabianp** [comment]
great!

**Pull request merged**
